### ISSUE TITLE
Amount <= 0.0001 display as 0

### ISSUE THREAD

**Issue by fmorency** [liftedinit/talib#306]
# OK
![2024-04-05_15-57](https://github.com/liftedinit/talib/assets/1102868/3171cc51-5729-4abe-ae45-3344bb56e308)

# NOT OK
![2024-04-05_15-57_1](https://github.com/liftedinit/talib/assets/1102868/3601adff-9dad-45ff-9502-52db833cad92)

**Comment by jgryffindor** [comment]
Fixed in: https://github.com/liftedinit/talib/pull/322
