### ISSUE TITLE
Limited number of transactions listed

### ISSUE THREAD

**Issue by fmorency** [liftedinit/talib#318]
1. Access https://talib.liftedinit.app
2. Search for `magh4n2sob62vrytamjenu5dvv5ecvfr3mk7umzlvtxeaptajj`
3. Notice the list of transactions is limited (there are more on the backend) without any support for pagination

One could expect to be able to navigate the full history of their transactions.

**Comment by jgryffindor** [comment]
Fixed in: https://github.com/liftedinit/talib/pull/322
