### ISSUE TITLE
Wrong argument type

### ISSUE THREAD

**Issue by fmorency** [liftedinit/talib#319]
https://github.com/liftedinit/talib/blob/530df346299e8499b500f2025d452b2d1b75331e/server/src/utils/protocol/attributes/ledger/ledger.send.ts#L8

The type is wrong according to 

https://github.com/many-protocol/specification/blob/7f78e835839c415fe563cb5a01a50f63330de5b1/attributes/network/cddl/2_ledger.cddl#L12

We should report it as a string and handle the numeral conversion on the client side.

**Comment by jgryffindor** [comment]
This was resolved in a previous update. 
https://github.com/liftedinit/talib/blob/2ebffdd7875ee26b912a3d336c7f1942752870cb/server/src/utils/protocol/attributes/ledger/ledger.send.ts#L6-L11
